# Generated by Django 3.2.7 on 2021-09-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product_gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
