# Generated by Django 3.2.6 on 2021-09-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='userprofile/default-avatar.jpg', upload_to='userprofile/'),
        ),
    ]
