# Generated by Django 3.2.6 on 2021-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='address_line2',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True),
        ),
    ]
