# Generated by Django 3.2.6 on 2021-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('orders', '0003_auto_20210825_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='variation',
        ),
        migrations.AddField(
            model_name='order_product',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
